import type { Metadata } from "next";
import { Josefin_Sans } from 'next/font/google';
import "./globals.css";

const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'], // optional
  style: ['normal', 'italic'], // optional
  variable: '--font-josefin-sans', // optional (for CSS custom properties)
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${josefinSans.className} bg-white dark:bg-[#171823]`}>
        {children}
      </body>
    </html>
  );
}
